# Analyse des Symétries de la Molécule LiRhO2

## Introduction
Dans ce notebook, nous allons étudier l'effet de trois éléments de symétrie différents sur les atomes de la molécule LiRhO2 (mp-14115). Nous utiliserons la structure conventionnelle pour mieux visualiser les symétries et vérifierons manuellement les résultats obtenus.

In [1]:
# Importation des bibliothèques nécessaires
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view

## Récupération de la Structure Cristalline

In [2]:
# Récupération de la structure
with MPRester("SIW188zlPeNPO5kUv2cgLJFjL9GATHk3") as m:
    structure = m.get_structure_by_material_id("mp-14115")

# Conversion en structure conventionnelle
conv_struc = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

## Visualisation de la Structure

In [3]:
# Visualisation de la structure
view = quick_view(conv_struc, "packed", conventional=True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

## Analyse des Symétries

### 1. Rotation de 120° autour de l'axe Z sur l'atome Li

$$
\begin{bmatrix} 0 & -1 & 0 \\ 1 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix} \times \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} -y \\ x-y \\ z \end{bmatrix}
$$

In [4]:
i_atom = 1  # Atome Li
i_symmop = 3  # Opération de symétrie : rotation

symmop = symmops[i_symmop - 1]
pos_init = conv_struc.sites[i_atom - 1].frac_coords
pos_final = symmop.operate(pos_init)
matrix = symmop.rotation_matrix
tau = symmop.translation_vector

print(f"Position initiale de Li : {pos_init}")
print(f"Matrice de transformation :\n{matrix}")
print(f"Vecteur tau : {tau}")
print(f"Position finale de Li : {pos_final}")

Position initiale de Li : [0.33333333 0.66666667 0.16666667]
Matrice de transformation :
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
Vecteur tau : [0. 0. 0.]
Position finale de Li : [-0.66666667 -0.33333333  0.16666667]


### Vérification Manuelle

In [5]:
# Vérification manuelle du calcul
pos_computed = np.dot(matrix, pos_init) + tau
print(f"Position calculée manuellement : {pos_computed}")

Position calculée manuellement : [-0.66666667 -0.33333333  0.16666667]


In [6]:
view1 = quick_view(conv_struc, "packed", conventional=True)
display(view1)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [7]:
view1.script('select lithium; color palegreen')
view1.script('draw SYMOP ' + str(3) + ' {atomno = ' + str(1) + '}')

### 2. Roto-réflexion sur l'atome Rh
- Réflexion par rapport au plan xy
- Rotation de 180° autour de l'axe z 


$$
\begin{bmatrix} 0 & -1 & 0 \\ -1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix} \times \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} -y \\ -x \\ z \end{bmatrix}
$$

In [8]:
i_atom = 5  # Atome Rh
i_symmop = 8  # Opération de symétrie : réflexion et rotation

symmop = symmops[i_symmop - 1]
pos_init = conv_struc.sites[i_atom - 1].frac_coords
pos_final = symmop.operate(pos_init)
matrix = symmop.rotation_matrix
tau = symmop.translation_vector

print(f"Position initiale de Rh : {pos_init}")
print(f"Matrice de transformation :\n{matrix}")
print(f"Vecteur tau : {tau}")
print(f"Position finale de Rh : {pos_final}")

Position initiale de Rh : [0.66666667 0.33333333 0.33333333]
Matrice de transformation :
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Vecteur tau : [0. 0. 0.]
Position finale de Rh : [-0.33333333 -0.66666667  0.33333333]


### Vérification Manuelle

In [9]:
# Vérification manuelle du calcul
pos_computed = np.dot(matrix, pos_init) + tau
print(f"Position calculée manuellement : {pos_computed}")

Position calculée manuellement : [-0.33333333 -0.66666667  0.33333333]


In [10]:
view2 = quick_view(conv_struc, "packed", conventional=True)
display(view2)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [17]:
# Appliquer la réflexion par rapport au plan XY
view2.script('draw PLANE xy')
view2.script('select rhodium; color blue') 

# Appliquer la rotation de 180° autour de l'axe Z
view2.script('rotate z 180') 
view2.script('draw SYMOP 8 {atomno = 5}') 


### 3. Inversion par rapport à l'origine sur l'atome O

$$
\begin{bmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & -1 \end{bmatrix} \times \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} -x \\ -y \\ -z \end{bmatrix}
$$

In [12]:
i_atom = 7  # Atome O
i_symmop = 14  # Opération de symétrie : inversion

symmop = symmops[i_symmop - 1]
pos_init = conv_struc.sites[i_atom - 1].frac_coords
pos_final = symmop.operate(pos_init)
matrix = symmop.rotation_matrix
tau = symmop.translation_vector

print(f"Position initiale de O : {pos_init}")
print(f"Matrice de transformation :\n{matrix}")
print(f"Vecteur tau : {tau}")
print(f"Position finale de O : {pos_final}")

Position initiale de O : [0.66666667 0.33333333 0.07725423]
Matrice de transformation :
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Vecteur tau : [0.66666667 0.33333333 0.33333333]
Position finale de O : [0.        0.        0.2560791]


### Vérification Manuelle

In [13]:
# Vérification manuelle du calcul
pos_computed = np.dot(matrix, pos_init) + tau
print(f"Position calculée manuellement : {pos_computed}")

Position calculée manuellement : [0.        0.        0.2560791]


In [14]:
view3 = quick_view(conv_struc, "packed", conventional=True)
display(view3)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [16]:
view3.script('select oxygen; color red')  # Atome O en rouge
view3.script('draw SYMOP 11 {atomno = 7}')  # Application de la symétrie sur O

# Ajout de la flèche de translation, affichée dans une autre couleur (par exemple, bleu)
view3.script('select oxygen; color blue')  # Changer la couleur de la flèche en bleu
view3.script('draw arrow 0.66666667 0.33333333 0.07725423 0.66666667 0.33333333 0.33333333; color blue')

## Conclusion
Ce notebook a analysé l'effet des opérations de symétrie sur la structure cristalline de LiRhO₂, en vérifiant manuellement les transformations et en les illustrant via Jupyter-JSmol. Cette approche permet de mieux comprendre l’impact de la symétrie sur les propriétés des matériaux.